-- Local development schema (SQLite).
--
-- The production target is PostgreSQL — packages/database/migrations. This file
-- exists because the development environment has no Postgres and no Docker, and
-- a mail client that cannot be run is a mail client that cannot be verified.
--
-- The two are kept in step by `schema-parity.spec.mjs`, which fails if either
-- side gains or loses a table. Column-level drift is not caught, so treat the
-- Postgres migration as authoritative when they disagree.
--
-- Differences that are deliberate, not drift:
--   * UUIDs are TEXT. SQLite has no uuid type; ids are generated by the app.
--   * JSONB is TEXT holding JSON. SQLite has json1 functions over TEXT.
--   * TIMESTAMPTZ is TEXT holding RFC 3339 UTC, which sorts lexicographically.
--   * No partitioning. SQLite has none; the volume this matters at is Postgres.

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

-- ── Tenancy and identity ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS tenants (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  slug            TEXT NOT NULL UNIQUE,
  plan            TEXT NOT NULL DEFAULT 'free',
  status          TEXT NOT NULL DEFAULT 'active',
  max_storage_mb  INTEGER NOT NULL DEFAULT 10240,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS domains (
  id              TEXT PRIMARY KEY,
  tenant_id       TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name            TEXT NOT NULL UNIQUE,
  status          TEXT NOT NULL DEFAULT 'pending',
  mx_verified     INTEGER NOT NULL DEFAULT 0,
  spf_verified    INTEGER NOT NULL DEFAULT 0,
  dkim_verified   INTEGER NOT NULL DEFAULT 0,
  dmarc_verified  INTEGER NOT NULL DEFAULT 0,
  dkim_selector   TEXT,
  dkim_public_key TEXT,
  dkim_private_key_enc BLOB,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS domains_tenant_idx ON domains(tenant_id);

CREATE TABLE IF NOT EXISTS users (
  id              TEXT PRIMARY KEY,
  tenant_id       TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  domain_id       TEXT NOT NULL REFERENCES domains(id),
  email           TEXT NOT NULL UNIQUE,
  display_name    TEXT NOT NULL,
  -- scrypt, stored as `scrypt$N$r$p$salt$hash`. Null for a passkey-only
  -- account: a dummy hash would be something an attacker can attempt.
  password_hash   TEXT,
  role            TEXT NOT NULL DEFAULT 'user',
  status          TEXT NOT NULL DEFAULT 'active',
  quota_bytes     INTEGER NOT NULL DEFAULT 10737418240,
  used_bytes      INTEGER NOT NULL DEFAULT 0,
  timezone        TEXT NOT NULL DEFAULT 'UTC',
  language        TEXT NOT NULL DEFAULT 'en',
  settings        TEXT NOT NULL DEFAULT '{}',
  mfa_enabled     INTEGER NOT NULL DEFAULT 0,
  mfa_secret_enc  BLOB,
  email_verified  INTEGER NOT NULL DEFAULT 0,
  last_login_at   TEXT,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS users_tenant_idx ON users(tenant_id);

CREATE TABLE IF NOT EXISTS sessions (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- SHA-256 of the token. The plaintext exists only in the user's cookie, so a
  -- dump of this table is not a set of usable credentials.
  token_hash      TEXT NOT NULL UNIQUE,
  ip_address      TEXT,
  user_agent      TEXT,
  device_name     TEXT,
  expires_at      TEXT NOT NULL,
  revoked_at      TEXT,
  created_at      TEXT NOT NULL,
  last_seen_at    TEXT
);
CREATE INDEX IF NOT EXISTS sessions_user_idx ON sessions(user_id);
CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON sessions(expires_at);

-- ── Mail store ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS mailboxes (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  -- JMAP role: inbox|sent|drafts|archive|trash|junk, or NULL for user folders.
  role            TEXT,
  parent_id       TEXT REFERENCES mailboxes(id) ON DELETE CASCADE,
  sort_order      INTEGER NOT NULL DEFAULT 0,
  created_at      TEXT NOT NULL,
  UNIQUE (user_id, name, parent_id)
);
CREATE INDEX IF NOT EXISTS mailboxes_user_idx ON mailboxes(user_id);
-- One mailbox per role per user. Two inboxes is a corruption, not a preference.
CREATE UNIQUE INDEX IF NOT EXISTS mailboxes_role_uniq
  ON mailboxes(user_id, role) WHERE role IS NOT NULL;

CREATE TABLE IF NOT EXISTS threads (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Normalised subject, used only as a LAST resort when the References chain
  -- is absent. Subject alone never groups messages — see lib/server/threading.
  subject_key     TEXT NOT NULL,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS threads_user_idx ON threads(user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS messages (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  thread_id       TEXT NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
  mailbox_id      TEXT NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
  -- RFC 5322 Message-ID, angle brackets stripped. Unique per user so a message
  -- delivered twice is stored once.
  message_id      TEXT,
  in_reply_to     TEXT,
  references_list TEXT,
  from_name       TEXT,
  from_email      TEXT NOT NULL,
  subject         TEXT NOT NULL DEFAULT '',
  preview         TEXT NOT NULL DEFAULT '',
  body_text       TEXT,
  body_html       TEXT,
  size_bytes      INTEGER NOT NULL DEFAULT 0,
  is_read         INTEGER NOT NULL DEFAULT 0,
  is_flagged      INTEGER NOT NULL DEFAULT 0,
  is_draft        INTEGER NOT NULL DEFAULT 0,
  is_answered     INTEGER NOT NULL DEFAULT 0,
  has_attachment  INTEGER NOT NULL DEFAULT 0,
  -- Authentication-Results, as received. Never recomputed on the client.
  spf_result      TEXT NOT NULL DEFAULT 'none',
  dkim_result     TEXT NOT NULL DEFAULT 'none',
  dmarc_result    TEXT NOT NULL DEFAULT 'none',
  arc_result      TEXT,
  tls_version     TEXT,
  display_name_spoof INTEGER NOT NULL DEFAULT 0,
  idn_homograph   INTEGER NOT NULL DEFAULT 0,
  snoozed_until   TEXT,
  scheduled_at    TEXT,
  received_at     TEXT NOT NULL,
  sent_at         TEXT,
  deleted_at      TEXT,
  created_at      TEXT NOT NULL,
  UNIQUE (user_id, message_id)
);
-- The list query: this user's mailbox, newest first. Covering enough that the
-- inbox does not touch the table for ordering.
CREATE INDEX IF NOT EXISTS messages_mailbox_idx
  ON messages(user_id, mailbox_id, received_at DESC);
CREATE INDEX IF NOT EXISTS messages_thread_idx ON messages(thread_id, received_at);
CREATE INDEX IF NOT EXISTS messages_unread_idx
  ON messages(user_id, mailbox_id) WHERE is_read = 0;
CREATE INDEX IF NOT EXISTS messages_flagged_idx
  ON messages(user_id) WHERE is_flagged = 1;
CREATE INDEX IF NOT EXISTS messages_msgid_idx ON messages(user_id, message_id);

CREATE TABLE IF NOT EXISTS message_recipients (
  id              TEXT PRIMARY KEY,
  message_id      TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  kind            TEXT NOT NULL CHECK (kind IN ('to', 'cc', 'bcc', 'reply-to')),
  name            TEXT,
  email           TEXT NOT NULL,
  position        INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS recipients_message_idx ON message_recipients(message_id);
CREATE INDEX IF NOT EXISTS recipients_email_idx ON message_recipients(email);

CREATE TABLE IF NOT EXISTS attachments (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Null while the upload belongs to an unsent draft.
  message_id      TEXT REFERENCES messages(id) ON DELETE CASCADE,
  filename        TEXT NOT NULL,
  -- The type the SERVER determined from the file's magic bytes, never the one
  -- the browser claimed.
  content_type    TEXT NOT NULL,
  declared_type   TEXT,
  size_bytes      INTEGER NOT NULL,
  -- SHA-256 of the content: integrity check and deduplication key.
  checksum        TEXT NOT NULL,
  storage_key     TEXT NOT NULL,
  is_inline       INTEGER NOT NULL DEFAULT 0,
  content_id      TEXT,
  scan_status     TEXT NOT NULL DEFAULT 'pending'
                    CHECK (scan_status IN ('pending', 'clean', 'infected', 'skipped', 'failed')),
  created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS attachments_message_idx ON attachments(message_id);
CREATE INDEX IF NOT EXISTS attachments_user_idx ON attachments(user_id);

CREATE TABLE IF NOT EXISTS labels (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  color           TEXT NOT NULL DEFAULT 'gray',
  is_hidden       INTEGER NOT NULL DEFAULT 0,
  created_at      TEXT NOT NULL,
  UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS message_labels (
  message_id      TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  label_id        TEXT NOT NULL REFERENCES labels(id) ON DELETE CASCADE,
  PRIMARY KEY (message_id, label_id)
);
CREATE INDEX IF NOT EXISTS message_labels_label_idx ON message_labels(label_id);

-- Full-text search over the parts a person actually searches. `content=''`
-- makes this contentless: the index stores terms, the messages table stores
-- text, and there is exactly one copy of every body.
CREATE VIRTUAL TABLE IF NOT EXISTS messages_fts USING fts5(
  subject, body, from_addr, to_addr, filenames,
  content='',
  tokenize='porter unicode61'
);

-- ── Operations ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS delivery_events (
  id              TEXT PRIMARY KEY,
  user_id         TEXT,
  message_id      TEXT,
  sender          TEXT NOT NULL,
  recipient       TEXT NOT NULL,
  event_type      TEXT NOT NULL,
  smtp_code       INTEGER,
  smtp_response   TEXT,
  remote_mx       TEXT,
  tls_version     TEXT,
  metadata        TEXT NOT NULL DEFAULT '{}',
  created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS delivery_events_user_idx ON delivery_events(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS outbound_queue (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message_id      TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  status          TEXT NOT NULL DEFAULT 'queued'
                    CHECK (status IN ('queued', 'sending', 'sent', 'failed', 'cancelled')),
  attempts        INTEGER NOT NULL DEFAULT 0,
  next_attempt_at TEXT NOT NULL,
  last_error      TEXT,
  -- Supplied by the client; a retried submit reuses it so a timeout cannot
  -- send the same message twice.
  idempotency_key TEXT UNIQUE,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS outbound_pending_idx
  ON outbound_queue(status, next_attempt_at);

CREATE TABLE IF NOT EXISTS audit_logs (
  id              TEXT PRIMARY KEY,
  user_id         TEXT,
  action          TEXT NOT NULL,
  resource_type   TEXT,
  resource_id     TEXT,
  ip_address      TEXT,
  user_agent      TEXT,
  details         TEXT NOT NULL DEFAULT '{}',
  severity        TEXT NOT NULL DEFAULT 'info',
  created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS audit_user_idx ON audit_logs(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS security_events (
  id              TEXT PRIMARY KEY,
  user_id         TEXT,
  event_type      TEXT NOT NULL,
  source_ip       TEXT,
  target_user     TEXT,
  details         TEXT NOT NULL DEFAULT '{}',
  severity        TEXT NOT NULL DEFAULT 'warning',
  resolved        INTEGER NOT NULL DEFAULT 0,
  created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS security_events_idx ON security_events(created_at DESC);

CREATE TABLE IF NOT EXISTS blocked_ips (
  id              TEXT PRIMARY KEY,
  ip_address      TEXT NOT NULL UNIQUE,
  reason          TEXT NOT NULL,
  blocked_until   TEXT,
  created_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS api_keys (
  id              TEXT PRIMARY KEY,
  tenant_id       TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id         TEXT REFERENCES users(id) ON DELETE SET NULL,
  name            TEXT NOT NULL,
  key_hash        TEXT NOT NULL UNIQUE,
  key_prefix      TEXT NOT NULL,
  scopes          TEXT NOT NULL DEFAULT '[]',
  rate_limit      INTEGER NOT NULL DEFAULT 1000,
  expires_at      TEXT,
  last_used_at    TEXT,
  created_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS webhooks (
  id              TEXT PRIMARY KEY,
  tenant_id       TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  url             TEXT NOT NULL,
  events          TEXT NOT NULL DEFAULT '[]',
  secret_enc      BLOB NOT NULL,
  enabled         INTEGER NOT NULL DEFAULT 1,
  failure_count   INTEGER NOT NULL DEFAULT 0,
  last_triggered  TEXT,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS aliases (
  id              TEXT PRIMARY KEY,
  domain_id       TEXT NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
  source_address  TEXT NOT NULL UNIQUE,
  destination     TEXT NOT NULL,
  alias_type      TEXT NOT NULL DEFAULT 'standard',
  enabled         INTEGER NOT NULL DEFAULT 1,
  created_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS distribution_lists (
  id              TEXT PRIMARY KEY,
  domain_id       TEXT NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
  address         TEXT NOT NULL UNIQUE,
  name            TEXT NOT NULL,
  members         TEXT NOT NULL DEFAULT '[]',
  allow_external  INTEGER NOT NULL DEFAULT 0,
  moderated       INTEGER NOT NULL DEFAULT 0,
  moderators      TEXT NOT NULL DEFAULT '[]',
  created_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS mail_rules (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  priority        INTEGER NOT NULL DEFAULT 0,
  conditions      TEXT NOT NULL,
  actions         TEXT NOT NULL,
  enabled         INTEGER NOT NULL DEFAULT 1,
  sieve_script    TEXT,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS signatures (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  html_content    TEXT NOT NULL,
  text_content    TEXT NOT NULL,
  is_default      INTEGER NOT NULL DEFAULT 0,
  created_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS vacation_responders (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  subject         TEXT NOT NULL,
  html_body       TEXT NOT NULL,
  text_body       TEXT NOT NULL,
  start_date      TEXT,
  end_date        TEXT,
  enabled         INTEGER NOT NULL DEFAULT 0,
  exclude_contacts INTEGER NOT NULL DEFAULT 1,
  created_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS passkeys (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  credential_id   BLOB NOT NULL UNIQUE,
  public_key      BLOB NOT NULL,
  name            TEXT NOT NULL,
  sign_count      INTEGER NOT NULL DEFAULT 0,
  transports      TEXT NOT NULL DEFAULT '[]',
  created_at      TEXT NOT NULL,
  last_used_at    TEXT
);

-- ── Storage federation ────────────────────────────────────────────────────
--
-- External providers are the source of truth for their own bytes. These tables
-- hold the connection, where it is mounted, who can see the mount, and an
-- index of items — never a copy of the content, unless the user explicitly
-- imports it (which makes it a native file with its own row elsewhere).

CREATE TABLE IF NOT EXISTS storage_connections (
  id              TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  -- NULL for an organization-owned connection created by an admin.
  owner_user_id   TEXT REFERENCES users(id) ON DELETE CASCADE,
  provider        TEXT NOT NULL,
  display_name    TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'disconnected'
                    CHECK (status IN ('active','degraded','auth_required','revoked','unreachable','disconnected')),
  status_detail   TEXT,
  -- AES-256-GCM envelope, bound to this row's id as AAD. A dump of this table
  -- is not a usable set of provider credentials.
  encrypted_credentials TEXT,
  last_sync_at    TEXT,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS storage_connections_org_idx ON storage_connections(organization_id);
CREATE INDEX IF NOT EXISTS storage_connections_owner_idx ON storage_connections(owner_user_id);

CREATE TABLE IF NOT EXISTS storage_mounts (
  id              TEXT PRIMARY KEY,
  connection_id   TEXT NOT NULL REFERENCES storage_connections(id) ON DELETE CASCADE,
  organization_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  root_path       TEXT NOT NULL DEFAULT '/',
  -- 'private' is the default on purpose: connecting a personal account must
  -- not expose it to the whole organization.
  visibility      TEXT NOT NULL DEFAULT 'private'
                    CHECK (visibility IN ('private','organization','group','users')),
  granted_group_ids TEXT NOT NULL DEFAULT '[]',
  granted_user_ids  TEXT NOT NULL DEFAULT '[]',
  max_role        TEXT NOT NULL DEFAULT 'viewer'
                    CHECK (max_role IN ('viewer','commenter','contributor','content_manager','manager')),
  indexing        TEXT NOT NULL DEFAULT 'metadata'
                    CHECK (indexing IN ('disabled','metadata','metadata_and_text','full_content')),
  created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS storage_mounts_connection_idx ON storage_mounts(connection_id);
CREATE INDEX IF NOT EXISTS storage_mounts_org_idx ON storage_mounts(organization_id);

CREATE TABLE IF NOT EXISTS storage_items (
  id              TEXT PRIMARY KEY,
  connection_id   TEXT NOT NULL REFERENCES storage_connections(id) ON DELETE CASCADE,
  -- The provider's id, unique only WITHIN a connection. Never a primary key:
  -- two providers will collide.
  external_id     TEXT NOT NULL,
  parent_external_id TEXT,
  name            TEXT NOT NULL,
  mime_type       TEXT NOT NULL DEFAULT 'application/octet-stream',
  size_bytes      INTEGER,
  is_folder       INTEGER NOT NULL DEFAULT 0,
  modified_at     TEXT,
  web_url         TEXT,
  indexed_at      TEXT,
  created_at      TEXT NOT NULL,
  UNIQUE (connection_id, external_id)
);
CREATE INDEX IF NOT EXISTS storage_items_parent_idx ON storage_items(connection_id, parent_external_id);

CREATE TABLE IF NOT EXISTS storage_sync_states (
  connection_id   TEXT PRIMARY KEY REFERENCES storage_connections(id) ON DELETE CASCADE,
  -- Provider change cursor. Incremental sync depends on this; a full re-crawl
  -- on every request is what it exists to avoid.
  change_cursor   TEXT,
  last_sync_at    TEXT,
  last_error      TEXT,
  items_indexed   INTEGER NOT NULL DEFAULT 0,
  updated_at      TEXT NOT NULL
);
