import "server-only";
import { createHash, randomUUID } from "node:crypto";
import { createReadStream, createWriteStream } from "node:fs";
import { copyFile, mkdir, rename, rm, stat, statfs, unlink, writeFile, readFile } from "node:fs/promises";
import { dirname, resolve, sep } from "node:path";
import { pipeline } from "node:stream/promises";
import { Readable } from "node:stream";
import {
  isBackendError,
  isNetworkFilesystem,
  ObjectNotFoundError,
  StorageUnavailableError,
  type CapacityReport,
  type HealthReport,
  type ObjectStat,
  type StorageProvider,
  type StoredObject,
} from "./provider";

/**
 * Filesystem-backed storage.
 *
 * This is the base for every POSIX-path backend, including NFS — from Node's
 * point of view an NFS export IS a directory, and the difference is entirely
 * operational (is it mounted, how slow is it, what happens when the server
 * goes away). Those differences live in `NfsStorage`, which extends this.
 *
 * Nothing here loads a whole object into memory. A 100 MB attachment on a
 * server handling twenty concurrent uploads is 2 GB of heap if you do.
 */
export class FilesystemStorage implements StorageProvider {
  readonly name: string;
  protected readonly root: string;

  constructor(root: string, name = "filesystem") {
    this.root = resolve(process.cwd(), root);
    this.name = name;
  }

  /**
   * Resolve a key to a path, refusing anything that escapes the root.
   *
   * Keys are generated by `newStorageKey` and are safe by construction, but
   * this is the last line before the filesystem and it costs one string
   * comparison — so it checks anyway rather than trusting every future caller.
   */
  protected pathFor(key: string): string {
    const full = resolve(this.root, key);
    if (full !== this.root && !full.startsWith(this.root + sep)) {
      throw new Error("Refusing to resolve a storage key outside the storage root");
    }
    return full;
  }

  /**
   * Translate a filesystem error into the right domain error.
   *
   * "The object is missing" and "the backend is unreachable" demand opposite
   * responses from the caller, so they must not arrive as the same exception.
   */
  protected translate(error: unknown, key: string): never {
    if (isBackendError(error)) {
      throw new StorageUnavailableError(
        `Storage backend "${this.name}" is not responding (${(error as NodeJS.ErrnoException).code}).`,
        error
      );
    }
    if ((error as NodeJS.ErrnoException).code === "ENOENT") throw new ObjectNotFoundError(key);
    throw error;
  }

  /**
   * Write to a temporary name, fsync, then rename into place.
   *
   * A reader must never observe a half-written object. `rename` within a
   * filesystem is atomic, so the object appears complete or not at all — and
   * a crash mid-upload leaves a `.part` file for the reconciler rather than a
   * truncated file that looks real.
   */
  async put(stream: Readable, key: string): Promise<StoredObject> {
    const path = this.pathFor(key);
    const temp = `${path}.${randomUUID()}.part`;

    try {
      await mkdir(dirname(path), { recursive: true });

      const hash = createHash("sha256");
      let size = 0;

      // Hash and measure in flight, so the bytes are read exactly once.
      const measured = new Readable({ read() {} });
      stream.on("data", (chunk: Buffer) => {
        hash.update(chunk);
        size += chunk.length;
        measured.push(chunk);
      });
      stream.on("end", () => measured.push(null));
      stream.on("error", (error) => measured.destroy(error));

      await pipeline(measured, createWriteStream(temp));
      await rename(temp, path);

      return { key, size, checksum: hash.digest("hex") };
    } catch (error) {
      // Never leave a partial file behind under the real key.
      await rm(temp, { force: true }).catch(() => undefined);
      return this.translate(error, key);
    }
  }

  async get(key: string): Promise<Readable> {
    const path = this.pathFor(key);
    try {
      await stat(path);
    } catch (error) {
      return this.translate(error, key);
    }
    return createReadStream(path);
  }

  async getRange(key: string, start: number, end?: number): Promise<Readable> {
    const path = this.pathFor(key);
    try {
      await stat(path);
    } catch (error) {
      return this.translate(error, key);
    }
    // `end` is inclusive here and in HTTP Range, so it passes straight through.
    return createReadStream(path, end === undefined ? { start } : { start, end });
  }

  async delete(key: string): Promise<void> {
    try {
      await unlink(this.pathFor(key));
    } catch (error) {
      // Deleting something already gone is the desired end state.
      if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
      this.translate(error, key);
    }
  }

  async exists(key: string): Promise<boolean> {
    try {
      await stat(this.pathFor(key));
      return true;
    } catch (error) {
      // An unreachable backend is not the same as an absent object, and
      // returning false here would let a caller conclude the file was deleted.
      if (isBackendError(error)) this.translate(error, key);
      return false;
    }
  }

  async stat(key: string): Promise<ObjectStat | null> {
    try {
      const info = await stat(this.pathFor(key));
      return { key, size: info.size, modifiedAt: info.mtime };
    } catch (error) {
      if (isBackendError(error)) this.translate(error, key);
      return null;
    }
  }

  async move(fromKey: string, toKey: string): Promise<void> {
    const to = this.pathFor(toKey);
    try {
      await mkdir(dirname(to), { recursive: true });
      await rename(this.pathFor(fromKey), to);
    } catch (error) {
      // EXDEV: the two paths are on different filesystems, so rename cannot
      // work. Copy-then-delete is the correct fallback, not a failure.
      if ((error as NodeJS.ErrnoException).code === "EXDEV") {
        await this.copy(fromKey, toKey);
        await this.delete(fromKey);
        return;
      }
      this.translate(error, fromKey);
    }
  }

  async copy(fromKey: string, toKey: string): Promise<void> {
    const to = this.pathFor(toKey);
    try {
      await mkdir(dirname(to), { recursive: true });
      await copyFile(this.pathFor(fromKey), to);
    } catch (error) {
      this.translate(error, fromKey);
    }
  }

  /** Real capacity, straight from the filesystem. Never estimated. */
  protected async capacity(): Promise<CapacityReport> {
    try {
      const fs = await statfs(this.root);
      const blockSize = Number(fs.bsize);
      const total = Number(fs.blocks) * blockSize;
      // `bavail` is space available to an UNPRIVILEGED process, which is what
      // this application actually is. `bfree` includes root's reserve and
      // would overstate what we can write.
      const available = Number(fs.bavail) * blockSize;
      return {
        totalBytes: total,
        availableBytes: available,
        usedBytes: total - available,
        totalInodes: Number(fs.files) || null,
        availableInodes: Number(fs.ffree) || null,
        filesystemType: Number(fs.type),
      };
    } catch {
      // Better to report nothing than to invent a capacity.
      return {
        totalBytes: null,
        availableBytes: null,
        usedBytes: null,
        totalInodes: null,
        availableInodes: null,
        filesystemType: null,
      };
    }
  }

  /**
   * Write, read back, compare, delete — and time it.
   *
   * A check that only stats the directory proves the mount exists, not that it
   * accepts writes. An NFS export can be present and read-only, or present and
   * silently failing writes, and both look fine to `stat`.
   */
  async healthCheck(): Promise<HealthReport> {
    const checkedAt = new Date().toISOString();
    const capacity = await this.capacity();
    const probeKey = `.health/${randomUUID()}`;
    const probePath = this.pathFor(probeKey);
    const payload = `health ${checkedAt}`;

    let readable = false;
    let writable = false;
    let latencyMs: number | null = null;
    let detail = "";

    const started = performance.now();
    try {
      await mkdir(dirname(probePath), { recursive: true });
      await writeFile(probePath, payload, "utf8");
      writable = true;

      const readBack = await readFile(probePath, "utf8");
      readable = readBack === payload;
      if (!readable) detail = "A probe object read back with different content.";

      latencyMs = Math.round((performance.now() - started) * 100) / 100;
    } catch (error) {
      const code = (error as NodeJS.ErrnoException).code ?? "unknown";
      detail = `Probe failed (${code}).`;
      // A read-only mount is degraded, not down: downloads still work.
      if (code === "EROFS" || code === "EACCES" || code === "EPERM") {
        try {
          await stat(this.root);
          readable = true;
          detail = `Storage is readable but not writable (${code}).`;
        } catch {
          readable = false;
        }
      }
    } finally {
      await rm(probePath, { force: true }).catch(() => undefined);
    }

    const state =
      readable && writable ? "healthy" : readable ? "degraded" : "unavailable";

    if (state === "healthy" && capacity.availableBytes !== null && capacity.totalBytes) {
      const freeRatio = capacity.availableBytes / capacity.totalBytes;
      if (freeRatio < 0.05) {
        detail = `Only ${(freeRatio * 100).toFixed(1)}% of capacity remains.`;
      }
    }

    return {
      provider: this.name,
      state,
      detail: detail || "Write, read-back and delete all succeeded.",
      checkedAt,
      latencyMs,
      readable,
      writable,
      capacity,
      mount: {
        path: this.root,
        mounted: readable || writable,
        isNetworkFilesystem: isNetworkFilesystem(capacity.filesystemType),
      },
    };
  }
}
